### ISSUE TITLE
YK feedback 

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-spring-boot#11]
- [x] Ask SME about servlet feature
- servlet feature is necessary for the web app
- [x] Location for server.xml (more explanation may be needed) 
- [x] Are all phases in liberty maven plugin in pom.xml necessary? / If we take them all away will it work? Also try liberty maven plugin 3.0 to minimize the pom.xml 
Change version 3.0.M1
- yes, the packaging and app itself don't work without these phases 
- [x] Clearly define two paths or split into two separate guides

**Comment by barecode** [comment]
I think these are resolved with the latest PR merge. I'll run through the guide again to confirm.

**Comment by barecode** [comment]
This should be ready to close.
