### ISSUE TITLE
Dev content review feedback 3

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-spring-boot#8]
- **Running the Spring Boot application on Open Liberty**
  - [x] add hotspot for the 2nd `spring-boot-application`
  - [x] hotspots not work
    - ` springBoot`
    - `9080`
- **Deploying the application to server**
  - [x] something wrong for `/staging, hotspot 0, hotspot 1, hotspot 2, hotspot 3, hotspot 4, hotspot 5, hotspot 6, hotspot 15`
  - [x] copies the `server` ... should have hotspot
- Dockerfile the last `COPY` missing a backslash char `\`

**Comment by gkwan-ibm** [comment]
More...
- **Getting started**
   - [ ] the repo name not right in both. Should the projectid be `spring-boot`
     - command action
      - right pane git clone

**Comment by barecode** [comment]
I think this is resolved. Let me know if you are good to close @gkwan-ibm
